name: Auto Update Toffee BD

on:
  schedule:
    # প্রতি ৫ মিনিট পর পর চেক ও আপডেট করবে
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Toffee BD files (No Cache)
        run: |
          TIMESTAMP=$(date +%s)
          # মূল রিপোজিটরির সঠিক ফাইলের নাম
          curl -H "Cache-Control: no-cache" -sL "https://raw.githubusercontent.com/srhady/toffee-bd/main/toffee_playlist.m3u?t=${TIMESTAMP}" -o toffee_playlist.m3u
          curl -H "Cache-Control: no-cache" -sL "https://raw.githubusercontent.com/srhady/toffee-bd/main/toffee_playlist.json?t=${TIMESTAMP}" -o toffee_playlist.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add toffee_playlist.m3u toffee_playlist.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update Toffee: $(date)" && git push origin main)
